### ISSUE TITLE
Walkie Textie

### ISSUE THREAD

**Issue by RcrdBrt** [noman-land/fake-news#1]
Hi there. After a brief research I have found no other means of contacting this usename, so pardon me if you find this inappropriate. Are you the guy who has been working on "Walkie Texties"? If so I'd like to have a chat with you. I've been doing a personal project that explores the same use-case as a decentralized and secure channel of communication for SMS-like messages. You can reach me out at riccardo@NICKNAME.com. My public GPG key is below if you want to use it.
Feel free to close this issue and ignore if this doesn't apply to you or whatever.

-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEXE3fRxYJKwYBBAHaRw8BAQdAiEaXfh3+8A+vyeXYfUItz+1Vwe5Pl3/k2LdB
c5nRnMi0JVJpY2NhcmRvIEJlcnRvIDxyaWNjYXJkb0ByY3JkYnJ0LmNvbT6IlgQT
FggAPhYhBK/59qJ8KnOUC5f4YGeX8bNgTRE4BQJcTd9HAhsDBQkB4TOABQsJCAcC
BhUKCQgLAgQWAgMBAh4BAheAAAoJEGeX8bNgTRE4RFcA/REkrJk7txHfNp5tyQVw
9TANa208pWVpI+UjPFD4BsTkAP9QTqwWtFpJ9ExBDLSS1Dt04UqRqsZFzdmuRN+W
NkFwCLg4BFxN30cSCisGAQQBl1UBBQEBB0CB6ayavXeb7Z7/i31nAT4+QklRLEjq
CkJke2y5HB7LDgMBCAeIfgQYFggAJhYhBK/59qJ8KnOUC5f4YGeX8bNgTRE4BQJc
Td9HAhsMBQkB4TOAAAoJEGeX8bNgTRE4a00A/3aOt+wsAJR8su3Npnkl5x4dnB29
O4uXjus25CYiE1PSAQCpT0lK1oxoCnYQi4X+AzCKe6SA8Yf2RQ4Y+06KneyVBpkC
DQReQDk5ARAArPZA5Vw/UVZj02pqD4NkWiQ7/nCn/ZlFmhfdeLCB+tlxP916LcXk
fsqEagfoo/4Q/2yw03bLmt3et7GLVr160u2oLvbKzVQH2LfZUTzDsHPmihhLSsm8
Z5TZcbNSy20lOM3XofMpkqAmb0Dme9kMQSbExHwxIp/L4ZPVSzInUEp4WJPqb8X4
N7VAx+bXnok7xrVWeepIdIn3rCKuTJPo+Wtb1QttJeQ6jwRU6kPzIs34yZnMYU3c
QvyRQ8lTEnD3pLVp/6R1t+DrEFLm6/qaiQ8pe6fIohupXI0j98+QYv/u+9/ZY8ui
UuFi3VY9vTySWmilmodtrV9CoZlSeap7LtPD4TMAd3W2x8P+AJ6gZh7WwgGLdh5b
s2P4M2y6mKZKxVjaptKIvLEySfk5SFFaejf6K5M8waf8/Iuo557cdw5b+4qrMmO4
8tfhL4T0NIRaIHHsvJW5G8N85tyWFHhXZiaxalhD6G9o/ei2wbETP8WBowLAFdsO
ppZIL6W8ztTvpgpQobK1xKvZHZK0IYdg9dHSwxm4PU3zCrSn0alscjnHvXyOqnbo
aKEEZR9Ddy9mfct2S8Y+MaRiw5C1toMqWCn4WRxw52l3UqTtLFTta+GZGmempTkO
+GFBZxME+E9/NKQJqJI2TnkJZ9932dPOcA2bDNnbaL+dC0omfiHl0lcAEQEAAYkC
NgQgAQgAIBYhBBT1E9o1fnK1fLuqrkQ8T8y8jnuhBQJeQDlHAh0CAAoJEEQ8T8y8
jnuhnHIQAKXPsJshngebz/sakr2NYWpS8oviCHZZHtCgsGRciSQN1au+rxXjb9w5
Fs8vnYgAJ2BPs47Ro/cdS4HBcZaYQyboBBj4/VUpEh7zDiZ+RQ2/cwXVyFh04UOq
ZEEzKrdyLHUgeM3vYXUWSIc0qp+3UgaJHcZd6iOnT6WYz1huAEuAm8grc3vdM6Mh
3j6L4kYV0ztKERk0uYSUTQ2dtvYEl1QUyTiAjFz8dObLdA3J/cP9+642nc49aKc/
M++PCC6MvHP1HgtPtZcdSInSz6gY69U/UsZVg2oviIVuEHdcfUZXVIMruk+xTqcK
HnUXlLEkJcwkZ5ov2HbhrkmJfFT7RUU6P9qirizmfzYpkQtFwqfZ9yBfk4kVfyu5
PmHFIzc5SFNJngm8gLS3sh5jZklD7IV2nICllYy2EmuPHpMuPhACawSEfttomTvL
qlL+RpECXbcZ4qdJe2fFJP4HprAmq9D6NhPkZkCyfBxVis98nIHzBbwR7neIE3Kc
KjN0QgwkFQX/rmurokEtF3W6hOd3HP8jnKj5/D+B7E6e3zYcbMf+xSTJbynFM8np
dOonjYdsnpIa3hjgBAE/4RKXkEZv07C06cwRncy0+3anzWei+iBWFrwU7T9THxts
CwGqheh8hOi74aqyGgmcDkEyHOv98Y+vHfloxHZV0vf1sJKjiT5ptCVSaWNjYXJk
byBCZXJ0byA8cmljY2FyZG9AcmNyZGJydC5jb20+iQJUBBMBCAA+FiEEFPUT2jV+
crV8u6quRDxPzLyOe6EFAl5AOTkCGyMFCQlmAYAFCwkIBwIGFQoJCAsCBBYCAwEC
HgECF4AACgkQRDxPzLyOe6Efhg//UXfSKFbhnd9wZMloELDqboEuipf4qhmImD2k
EO7C2Hjx0mCfVeQE5u1FWLzyvAEbSo2osItTprUdnZQRphNqMESHGvwdD9aJF+zX
u7kz2qQKoG59IShNjVkCTOeSDwl1O1lCqeQEM01OlZjoYaHORUB0w0MboVFy2xAX
LVRS2fZsdVKzMBt9Z83WMBZfkksAmqcKVf8jEgiq/do7ClxEa3t+CfpHSVoDBzlC
X3enafhgy8UlJg7YPiSRW9/BOzsLBFEH3QXSnOo7WFUxvvW829sDqbTSBU7PUgYL
hWbjXC47WDOpSL0VLxH0WW9NQWMKLrj5N//3qPINcaT+apAWA7/YClzINSRrvA7Q
nHbMy9b1c3TfJxwjQaWBnEpcPePbrbd4cL9S5hRkPcy/+2sGYTIExHhK6m/DdeAE
aQy/MQQfst1b0gl/4iTkn91p04rZGo3cDoQ3Sn9ZLfOtiB9syD9/hHLQfh6pV/yF
pSsx7tyoJiO1QDUbf4ixgWcGFqsIIBZpULs0+dDeGXHqmah2LBavO+mGD+4BOda7
MgGMvYq2Dh7HTjVBmVU+GRiBkR0SPeXIVr1+/MX9e5RPOCxMgStKIBlbJsPG0wpq
guzIOkmBOuR71IRBzbk5/4xqHUoXCPq+aaMuZNfLjZZTrhWOvRLOHZ7mjDAU2DiP
2Tq0G7C5Ag0EXkA5OQEQAK7gyo+yZ5+rveUCguAXpvRZMltVmtbNi10UhqMzXiHq
gqSnzbCLAaQk6dKRWPEO91KIbI7RS3QAxCHzFx2xGetsf3gC/+DnMuWSzmHQORDU
D5/EDNPEL+MtOCwz+S3oh5VZeNeGzy4DUwCjjN4+jRmlv4tmjzHgTJ75vfZY1WLG
LExMxA8RSNNGFexagaPuRbwfpPsL2u3xKTo31DBNoLdf4KuB1bQD03gJzQo6KA0p
3k+pmkjXj9VcmusjpO6N3phcZnXBmBhGV8H1LiupP2wsA2iSSCmA88WNUzl2Yf6G
kKhmAPkeT+IpB5Q5otjaPo0yorSAmt78ZEDAK/HdmMbXqlCEK7ZoMK/+rz2y1CX0
kIyw6XShHVQZNlCp0acInNcDf4Zuo6Qlx/lw/zPrmLHFup92BTDR0fHX6sbYcl/l
c9xn/G/nMDmLtrYXk+sBps7pA62XeVwJFIzNlW/0pwbnYfT52njvApveJoIZ/cMQ
NIpCw00oaVyYZGdnGzGQBGMtgY5qKF8G8HX3xm8Pz+KctIpANAv5P4VDiaM25nlG
2svX1dgRmMJ4pifyHmGze3X1IMvcfypYgKz+PthtN/Kb2ob2u4E1r0blQVbyM0GX
nthMsWDWrl3VKr1T7FOfOF0E+5Ql9a2ccOhm7WZ0u5exCpbowlQlbMTQ3gF9vGqF
ABEBAAGJAjwEGAEIACYWIQQU9RPaNX5ytXy7qq5EPE/MvI57oQUCXkA5OQIbDAUJ
CWYBgAAKCRBEPE/MvI57ocWAEACPsr691qVRZ3mrt2wGIB1MiRNAMwFVc26qqNQ9
gZCLKs8bVivmFqAZv5ZDu5gox0PqZajkQxeVA7pt/tdkxsgAPev2me+xh1d3dI0r
TGQou2Cq9FELJ/ZHlzNTQCHu5qRulKyDN5CTVPPmgpuaPYLmkEebaf354oEg5kLV
H7ZqUokKYiQN/+aIJsCgwZkaqBtTT4goRFQvNh7PYqxdTYy2mv0DWICjfuoDcNXX
Hy9jDZk3qTWDvMAQLutJX8PSK4PVOYUIUoZ0+p/VdLoo2IZFLC2HaKS2qfGtx1Mh
bk2pmvzJvupqHwG2B16Q8Rtjh5cfAgKuc7hZRLNk+YlegHBgq9bpMwN7ycwXbNz/
Gc0FBooo6C1ktdSBjaCKZpE3DdEyKyWUcaWWZ8KCiAnxBYkW5izXf0mTorXVTls5
aECUKA+sRfZWctfa4ETD31A3hnta8FtY1AbyTJ1/K1IHtzbJ4G2vSm+tZMGX3qBz
PBAjRIThu2ZdIKye9sASWPa3z/PjqxrlsluKKUAt8ktS/TFXs6s/v+faJfY3SaQk
qQi0qsLI44+i7ETcFVbutLCVuj/gkMp4oqB+LJYsiimaz1cWS98QSrZEauXY4NIT
eDOGNZ9EHPxNrqXqoXabHQTAIwpmr7IHTKAwxLSiXMfw+7AGJcO1f4g2fOOEsFVh
gJZeD5gzBF+NMl0WCSsGAQQB2kcPAQEHQHwMDIQz8ByBsFHRXoVJWABqGCx1J87Z
+qs4XhnQCcc4tGRSaWNjYXJkbyBCZXJ0byAoTWFpbiBrZXksIHRvIGJlIHVzZWQg
d2l0aCBteSBwZXJzb25hbCBwZXJzb25hbCBtYWlsIGFkZHJlc3MuKSA8cmljY2Fy
ZG9AcmNyZGJydC5jb20+iJYEExYIAD4WIQQlZ0BDhRA8MtUr6Daf9no74ec/BgUC
X40yXQIbAwUJA8JnAAULCQgHAgYVCgkICwIEFgIDAQIeAQIXgAAKCRCf9no74ec/
BlNkAP4zdqEKI1/BGDWyqakaQ5VLRQ1LhcDc0I3ma6RXUKOu9QEAwPpph61MLA9E
/SMRXzyeB+o4qpRNbGuICa8Glapx+g+4OARfjTJdEgorBgEEAZdVAQUBAQdAuFZU
C3ARuGs+0ApuF/DzuVpgAxAjWFh4KsV6G15EAXoDAQgHiH4EGBYIACYWIQQlZ0BD
hRA8MtUr6Daf9no74ec/BgUCX40yXQIbDAUJA8JnAAAKCRCf9no74ec/BoG2AP9y
3UzAXIcorfwiLJJVNvk8FbPzaQEKRvLDUhD5Rd8OmQEA8GEsdMmaBEiFhRlXLs74
N4aj2Pr9Xn+CQRbc/d+ngA4=
=Fieh
-----END PGP PUBLIC KEY BLOCK-----

**Comment by noman-land** [comment]
Hello @RcrdBrt. This is funny, thank you for reaching out. Sorry I didn't notice this earlier. I will email you about this shortly.
